FROM openjdk:8-jre-alpine

MAINTAINER delivery-engineering@netflix.com

RUN sed -i 's|http://dl-cdn.alpinelinux.org/alpine|https://mirrors.aliyun.com/alpine|g' /etc/apk/repositories


COPY ./orca-web/build/install/orca /opt/orca

RUN apk --no-cache add --update bash

RUN adduser -D -S spinnaker

USER spinnaker

CMD ["/opt/orca/bin/orca"]
